version: '3.8'

services:
  # Node.js 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      # 挂载源代码目录
      - /app/node_modules
      # 挂载 package.json 和 package-lock.json
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
 