version: '3.8'

services:
  # Node.js 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      # 挂载源代码目录
      - ./src:/app/src
      # 挂载 package.json 和 package-lock.json
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    # 开发环境使用 nodemon 实现热重载
    command: npm run start:dev

networks:
  app-network:
    driver: bridge 