name: Deploy to Server

on:
  push:
    branches: [ main ]  # 当推送到 main 分支时触发

jobs:
  deploy:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # 检查项目目录是否存在
          if [ ! -d "/www/video_conference_server" ]; then
            # 如果目录不存在，创建目录并克隆仓库
            mkdir -p /www/video_conference_server
            cd /www
            git clone https://github.com/kaijierepo/video_conference_server.git
          else
            # 如果目录存在，进入目录并拉取更新
            cd /www/video_conference_server
            git fetch --all
            git reset --hard origin/main
          fi

          # 创建或更新 .env 文件
          echo "MEDIASOUP_ANNOUNCED_IP=${{ secrets.MEDIASOUP_ANNOUNCED_IP }}" > .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          
          # 检查 Dockerfile.app 是否存在
          if [ ! -f "Dockerfile.app" ]; then
            echo "Dockerfile.app not found!"
            exit 1
          fi
          
          # 创建 Docker 网络（如果不存在）
          docker network create app-network || true

          # 清理所有未使用的构建缓存
          docker builder prune -f
          # 或者清理所有未使用的 Docker 资源
          docker system prune -f
          
          
          # 构建新的应用镜像 --no-cache
          docker build -t nestjs-app:latest -f Dockerfile.app . || exit 1

          # 停止并删除旧容器（如果存在）
          docker stop app-container || true
          docker rm app-container || true
          
          # 启动应用容器
          docker run -d \
            --name app-container \
            --network app-network \
            -p 3000:3000 \
            --restart unless-stopped \
            -e MEDIASOUP_ANNOUNCED_IP=${{ secrets.MEDIASOUP_ANNOUNCED_IP }} \
            -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
            -e NODE_ENV=production \
            nestjs-app:latest
          
           # 等待几秒钟让应用启动
          sleep 5
          
          # 查看容器状态和日志
          docker ps
          docker logs --tail 50 app-container
        

